In [104]:
# Ferry's life session DIY NN first step.
# 30-9-2020

# Modified to 2 dimensional arrays so we can transpose.

# Almost there!

import numpy as np
import math

# code below seen before can't remember where!
class Relu:
    def compute(self,m):
        return np.array([x if x > 0 else 0 for x in m[0]], ndmin=2)
    def differentiate(self,m):
        return np.array([1.0 if x > 0 else 0 for x in m[0]], ndmin=2)
    
class Sigmoid :
    def compute(self,m):
        return np.array([(1 /(1 + math.exp(-x))) for x in m[0]], ndmin=2)
    def differentiate(self,m):
        m = self.compute(m)
        return np.array([x * (1 - x) for x in m[0]], ndmin=2)

# You need more think maybe mse or simpler, tanh, linear, softmax
# # # # #
#  Tim  #
# # # # #
class Tanh:
    def compute(self, m):
        return np.array([((np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))) for x in m[0]],ndmin=2)
    def differentiate(self, m):
        m = self.compute(m)
        return  np.array([1- x ** 2 for x in m[0]], ndmin=2)

class logistic:
    def compute(self,m):
        return np.array([1/(1 + np.exp(-x)) for x in m[0]],ndmin=2)
    def differentiate(self,m):
        m = self.compute(m)
        return np.array([x * (1 - x)for x in m[0]],ndmin=2)


In [105]:
# A gift
class MeanSquaredError:
    def compute(self, target, prediction):
        esum = 0
        delta = np.subtract(target,prediction)
        for i in delta:
            esum += i ** 2
        return esum/len(delta)    
    def differentiate(self, prediction, target):
        return np.multiply(np.subtract(target, prediction), 2)


In [106]:
# What bias values?    

# Make-layer now returns a list, tuples are read-only
def make_layer(input_neurons, output_neurons, activation) :
    return [np.random.rand(output_neurons, input_neurons) - 0.5 , np.zeros(output_neurons) , activation]

# model definition ([ layers* ] , [ activations*])
def make_model(model_def) :
    layers = model_def[0]
    act = model_def[1]
    result = [] 
    for count , nr_neurons in enumerate(layers[:-1]) :
        res = make_layer(nr_neurons, layers[count+1], act[count] ) 
        result.append(res)
    return result

def feed_forward(input_layer,w,b,function) :
    return function.compute(np.add(np.dot(w,input_layer.T),b)) 

def model_predict(model, input_neurons) :
    res = np.array(input_neurons, ndmin=2) 
    for layer in model :
        res = feed_forward(res,layer[0],layer[1],layer[2]) 
    return res
        

In [107]:
# The next is not finished yet, missing the bias update see coding train or make your own pdf 

def model_fit(model,X,y): 
    results = [] 
    res = np.array(X, ndmin=2) 
    inputs = np.array(X, ndmin=2)
    lr = 0.01
    for layer in model :
        res = feed_forward(res,layer[0],layer[1],layer[2]) 
        results.append(res)
    #
    e = np.subtract(y,results[-1])
    hidden_errors = np.dot(model[-1][0].T, e.T)

    print(str(hidden_errors) + ' >>> ' + str(e)+' hidden_errors')
    
    # update weight in de second layer
    delta_who = lr * np.dot(e.T * model[-1][2].differentiate(results[-1]).T , results[-2])
    model[-1][0] += delta_who
    
    # update weights in the firts layer (Loop there is a loop in there.)
    delta_who = lr * np.dot(hidden_errors * model[-2][2].differentiate(results[-2]).T,inputs)
    model[-2][0] += delta_who
    
    
    # see pdf almost there!


In [108]:
#print(model)
model = make_model(([2,2,1] , [ Sigmoid(), Sigmoid() ]))

In [109]:
import random
# test with XOR
samples_list = [
    [[0,0], [0]],
    [[0,1], [1]],
    [[1,0], [1]],
    [[1,1], [0]]
]

# 1: TEST THE WEIGHT UPDATES. by prinbting the errors errors sshould go down.
element = random.sample(samples_list,1)
for i in range(10):
    print(element)
    error = model_fit(model,element[0][0], element[0][1])
    print(error)


[[[0, 1], [1]]]
[[0.03491674]
 [0.09781485]] >>> [[0.45761399]] hidden_errors
None
[[[0, 1], [1]]]
[[0.03518794]
 [0.09806094]] >>> [[0.45743128]] hidden_errors
None
[[[0, 1], [1]]]
[[0.0354588 ]
 [0.09830669]] >>> [[0.45724863]] hidden_errors
None
[[[0, 1], [1]]]
[[0.03572932]
 [0.09855212]] >>> [[0.45706605]] hidden_errors
None
[[[0, 1], [1]]]
[[0.03599949]
 [0.09879721]] >>> [[0.45688353]] hidden_errors
None
[[[0, 1], [1]]]
[[0.03626933]
 [0.09904197]] >>> [[0.45670107]] hidden_errors
None
[[[0, 1], [1]]]
[[0.03653883]
 [0.09928639]] >>> [[0.45651867]] hidden_errors
None
[[[0, 1], [1]]]
[[0.03680799]
 [0.09953049]] >>> [[0.45633634]] hidden_errors
None
[[[0, 1], [1]]]
[[0.03707681]
 [0.09977426]] >>> [[0.45615407]] hidden_errors
None
[[[0, 1], [1]]]
[[0.03734529]
 [0.1000177 ]] >>> [[0.45597186]] hidden_errors
None


In [110]:

print (model_predict(model, [0,1] ))

[[0.54421028]]


In [111]:
model = make_model(([2,2,1] , [ Relu(), Sigmoid() ]))

In [112]:
import random
# test with XOR
samples_list = [
    [[0,0], [0]],
    [[0,1], [1]],
    [[1,0], [1]],
    [[1,1], [0]]
]

# 1: TEST THE WEIGHT UPDATES. by prinbting the errors errors should go down.
element = random.sample(samples_list,1)
for i in range(10):
    print(element)
    error = model_fit(model,element[0][0], element[0][1])
    print(error)


[[[1, 0], [1]]]
[[ 0.07115825]
 [-0.18552383]] >>> [[0.52213921]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.07141035]
 [-0.18524123]] >>> [[0.52207717]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.07166275]
 [-0.18495814]] >>> [[0.52201474]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.07191547]
 [-0.18467454]] >>> [[0.52195192]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.0721685 ]
 [-0.18439044]] >>> [[0.52188872]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.07242183]
 [-0.18410584]] >>> [[0.52182512]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.07267547]
 [-0.18382074]] >>> [[0.52176113]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.07292943]
 [-0.18353513]] >>> [[0.52169674]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.07318369]
 [-0.18324902]] >>> [[0.52163194]] hidden_errors
None
[[[1, 0], [1]]]
[[ 0.07343826]
 [-0.1829624 ]] >>> [[0.52156675]] hidden_errors
None


In [113]:

print (model_predict(model, [0,1] ))



[[0.5]]
